#+title: Always Learning
#+author: faultypointer

As I've said, [[https://faulty.carboxi.de/learning/][I love learning things]].
This folder contains notes and other files related to the stuff I learn.

* Currently
I'm currently learning about [[file:clisp/CLisp.org][common lisp]].

* So what have I learned then?
so empty...

* Logs
<2025-03-26 Wed> [[file:clisp/CLisp.org][common lisp]] finished chapter 3.
<2025-03-27 Thu> [[file:clisp/CLisp.org][common lisp]] finished chapter 4.
<2025-03-28 Fri> [[file:clisp/CLisp.org][common lisp]] nearly finished chapter 5.
<2025-03-29 Sat> [[file:clisp/CLisp.org][common lisp]] finished chapter 5 of practical common lisp. and intro to lisp chapter of [[file:clisp/piap/Piap.org][PIAP]].
<2025-03-30 Sun> common lisp a half of variable (6) chapter of practical common lisp as well as half of second chapter from piap. also made a file [[file:clisp/Vocab.org][Vocab.org]] for keeping common lisp functions, macros and other stuff i learn about
<2025-04-02 Wed> finally finished chapter 2 of piap
<2025-04-03 Thu> finished chapter 6 of practical common lisp
<2025-04-04 Fri> chapter 3 of piap started
<2025-04-05 Sat> more chapter 3 of piap
<2025-04-06 Sun> more chapter 3 of piap (very slow progress)
<2025-04-07 Mon> even more chapter 3 of piap (there is a lot of content in this chapter and not a lot of free time)
<2025-04-08 Tue> okay in next day or two chapter 3 is gonna finis. i promise. also ive neglecting the practical common lisp book
<2025-04-09 Wed> more chapter 3. i tried to attempt a question too but was too much for little time im giving this.
<2025-04-10 Thu> no more lisp for now [[file:~/git/Organ/Blog/Journal/all-in-rust.org][going all in on rust]] now.
<2025-04-11 Fri> too many linkedlist book second list finished.
<2025-04-14 Mon> havent logged here for a while. ive continuing with the linked list book. reached fifth list
* Should Learn about these stuff
- [ ] strace and how to use it
